BOARD_TAG = nano
BOARD_SUB = atmega328old
ARDMK_VENDOR = archlinux-arduino
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_CONF = /etc/avrdude.conf
ARDUINO_LIBS = 
ARDUINO_SKETCHBOOK = /home/torsten/Arduino/
CXXFLAGS_STD=-std=c++2a

include /usr/share/arduino/Arduino.mk
